name: CD

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: development
    env:
      STAGE: development
    steps:

      - name: Checkout Code Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci # Use `npm ci` instead of `npm install` for reproducibility

      - name: Install CDK CLI globally
        run: npm install -g aws-cdk #Global CLI installation (for cdk commands)

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: CDK Bootstrap
        run: |
          npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/us-east-1 \
            --toolkit-stack-name CDKToolkit \
            --require-approval never


      - name: CDK Synth
        run: cdk synth

      - name: CDK Deploy
        run: cdk deploy --require-approval never
